// This file is auto-generated by TanStack Router
// Do not edit manually - run `pnpm dev` to regenerate

import { createRootRoute } from '@tanstack/react-router'

export const routeTree = createRootRoute()
