import type { User } from '../types/user'

/** 50 mock users covering all roles (admin/manager/user) and statuses (active/inactive/pending) */
export const mockUsers: User[] = [
  { id: '1', name: 'Alice Johnson', email: 'alice.johnson@example.com', role: 'admin', status: 'active', createdAt: '2023-01-15' },
  { id: '2', name: 'Bob Smith', email: 'bob.smith@example.com', role: 'manager', status: 'active', createdAt: '2023-01-20' },
  { id: '3', name: 'Carol Williams', email: 'carol.williams@example.com', role: 'user', status: 'active', createdAt: '2023-02-05' },
  { id: '4', name: 'David Brown', email: 'david.brown@example.com', role: 'user', status: 'inactive', createdAt: '2023-02-10' },
  { id: '5', name: 'Eva Martinez', email: 'eva.martinez@example.com', role: 'manager', status: 'pending', createdAt: '2023-02-18' },
  { id: '6', name: 'Frank Davis', email: 'frank.davis@example.com', role: 'user', status: 'active', createdAt: '2023-03-01' },
  { id: '7', name: 'Grace Wilson', email: 'grace.wilson@example.com', role: 'admin', status: 'active', createdAt: '2023-03-12' },
  { id: '8', name: 'Henry Taylor', email: 'henry.taylor@example.com', role: 'user', status: 'pending', createdAt: '2023-03-20' },
  { id: '9', name: 'Iris Anderson', email: 'iris.anderson@example.com', role: 'manager', status: 'active', createdAt: '2023-04-02' },
  { id: '10', name: 'Jack Thomas', email: 'jack.thomas@example.com', role: 'user', status: 'inactive', createdAt: '2023-04-15' },
  { id: '11', name: 'Karen Jackson', email: 'karen.jackson@example.com', role: 'user', status: 'active', createdAt: '2023-04-22' },
  { id: '12', name: 'Leo White', email: 'leo.white@example.com', role: 'manager', status: 'inactive', createdAt: '2023-05-03' },
  { id: '13', name: 'Mia Harris', email: 'mia.harris@example.com', role: 'user', status: 'active', createdAt: '2023-05-14' },
  { id: '14', name: 'Nathan Martin', email: 'nathan.martin@example.com', role: 'admin', status: 'active', createdAt: '2023-05-25' },
  { id: '15', name: 'Olivia Garcia', email: 'olivia.garcia@example.com', role: 'user', status: 'pending', createdAt: '2023-06-08' },
  { id: '16', name: 'Paul Rodriguez', email: 'paul.rodriguez@example.com', role: 'user', status: 'active', createdAt: '2023-06-15' },
  { id: '17', name: 'Quinn Lewis', email: 'quinn.lewis@example.com', role: 'manager', status: 'active', createdAt: '2023-06-28' },
  { id: '18', name: 'Rachel Lee', email: 'rachel.lee@example.com', role: 'user', status: 'inactive', createdAt: '2023-07-05' },
  { id: '19', name: 'Sam Walker', email: 'sam.walker@example.com', role: 'user', status: 'active', createdAt: '2023-07-18' },
  { id: '20', name: 'Tina Hall', email: 'tina.hall@example.com', role: 'admin', status: 'pending', createdAt: '2023-07-30' },
  { id: '21', name: 'Uma Allen', email: 'uma.allen@example.com', role: 'user', status: 'active', createdAt: '2023-08-10' },
  { id: '22', name: 'Victor Young', email: 'victor.young@example.com', role: 'manager', status: 'active', createdAt: '2023-08-22' },
  { id: '23', name: 'Wendy Hernandez', email: 'wendy.hernandez@example.com', role: 'user', status: 'active', createdAt: '2023-09-01' },
  { id: '24', name: 'Xander King', email: 'xander.king@example.com', role: 'user', status: 'inactive', createdAt: '2023-09-14' },
  { id: '25', name: 'Yara Wright', email: 'yara.wright@example.com', role: 'manager', status: 'pending', createdAt: '2023-09-25' },
  { id: '26', name: 'Zoe Lopez', email: 'zoe.lopez@example.com', role: 'user', status: 'active', createdAt: '2023-10-05' },
  { id: '27', name: 'Aaron Hill', email: 'aaron.hill@example.com', role: 'admin', status: 'active', createdAt: '2023-10-18' },
  { id: '28', name: 'Bella Scott', email: 'bella.scott@example.com', role: 'user', status: 'active', createdAt: '2023-10-30' },
  { id: '29', name: 'Carlos Green', email: 'carlos.green@example.com', role: 'user', status: 'pending', createdAt: '2023-11-08' },
  { id: '30', name: 'Diana Adams', email: 'diana.adams@example.com', role: 'manager', status: 'active', createdAt: '2023-11-20' },
  { id: '31', name: 'Ethan Baker', email: 'ethan.baker@example.com', role: 'user', status: 'inactive', createdAt: '2023-12-01' },
  { id: '32', name: 'Fiona Gonzalez', email: 'fiona.gonzalez@example.com', role: 'user', status: 'active', createdAt: '2023-12-12' },
  { id: '33', name: 'George Nelson', email: 'george.nelson@example.com', role: 'manager', status: 'active', createdAt: '2023-12-24' },
  { id: '34', name: 'Hannah Carter', email: 'hannah.carter@example.com', role: 'admin', status: 'active', createdAt: '2024-01-05' },
  { id: '35', name: 'Ian Mitchell', email: 'ian.mitchell@example.com', role: 'user', status: 'pending', createdAt: '2024-01-18' },
  { id: '36', name: 'Julia Perez', email: 'julia.perez@example.com', role: 'user', status: 'active', createdAt: '2024-01-30' },
  { id: '37', name: 'Kevin Roberts', email: 'kevin.roberts@example.com', role: 'manager', status: 'inactive', createdAt: '2024-02-10' },
  { id: '38', name: 'Laura Turner', email: 'laura.turner@example.com', role: 'user', status: 'active', createdAt: '2024-02-22' },
  { id: '39', name: 'Mike Phillips', email: 'mike.phillips@example.com', role: 'user', status: 'active', createdAt: '2024-03-05' },
  { id: '40', name: 'Nina Campbell', email: 'nina.campbell@example.com', role: 'admin', status: 'active', createdAt: '2024-03-15' },
  { id: '41', name: 'Oscar Parker', email: 'oscar.parker@example.com', role: 'user', status: 'inactive', createdAt: '2024-03-28' },
  { id: '42', name: 'Penny Evans', email: 'penny.evans@example.com', role: 'manager', status: 'active', createdAt: '2024-04-08' },
  { id: '43', name: 'Rick Edwards', email: 'rick.edwards@example.com', role: 'user', status: 'pending', createdAt: '2024-04-20' },
  { id: '44', name: 'Sara Collins', email: 'sara.collins@example.com', role: 'user', status: 'active', createdAt: '2024-05-01' },
  { id: '45', name: 'Tom Stewart', email: 'tom.stewart@example.com', role: 'manager', status: 'active', createdAt: '2024-05-14' },
  { id: '46', name: 'Ursula Morris', email: 'ursula.morris@example.com', role: 'user', status: 'active', createdAt: '2024-05-25' },
  { id: '47', name: 'Vince Rogers', email: 'vince.rogers@example.com', role: 'admin', status: 'inactive', createdAt: '2024-06-05' },
  { id: '48', name: 'Wanda Reed', email: 'wanda.reed@example.com', role: 'user', status: 'active', createdAt: '2024-06-18' },
  { id: '49', name: 'Xavier Cook', email: 'xavier.cook@example.com', role: 'user', status: 'pending', createdAt: '2024-06-28' },
  { id: '50', name: 'Yvonne Morgan', email: 'yvonne.morgan@example.com', role: 'manager', status: 'active', createdAt: '2024-07-10' },
]
